name: sequencing-env

channels:
- conda-forge
- defaults

dependencies:
  - python>=3.7
  - pytest 
  - pytest-cov
  - sphinx
  - nbsphinx
  - numpy>=1.16
  - scipy 
  - cython
  - matplotlib 
  - jupyter
  - notebook
  - tqdm
  - lmfit
  - qutip>=4.5
  - pip
  - pip:
    - attrs>=20
    - sphinx_rtd_theme
    - colorednoise>=1.1.1